### ISSUE TITLE
mutli destinations

### ISSUE THREAD

**Issue by tkocher** [masc3d/btrfs-sxbackup#25]
Hi,

first of all I would like to thank for such a good script suite to create comfortable btrfs backups.
What I am currently miss is to use different backup destination. Assume in the backup maschines are different disk drives instead of raid, so it would be very nice to select the backupdestination by an argument or pass the config dir.

What is your opinion about his?

**Comment by masc3d** [comment]
I believe it's the same or similar requirement as mentioned [here](https://github.com/masc3d/btrfs-sxbackup/issues/9). can you confirm?

**Comment by masc3d** [comment]
I would still be curious about the concrete use case of backing up one source to multiple destination volumes on the same machine to understand the requirements.

**Comment by tkocher** [comment]
yes it is a duplicate :-)

well I would like to backup to 2 backup location to be endependent in case a backup station dies or have a disk error. I always had problems with SW Raid so far, as soon as a disc crashed raid was not affected as well. So 2 dedicated backup locations are better than 1 raid 1 backup location.

For me only one local subvolume snapshot would be enough

**Comment by masc3d** [comment]
[mdraid](https://raid.wiki.kernel.org/) has done an excellent job for me in the past for protection from drive failures. for multiple destinations you also need mutliple local snapshots because local and remote subvolume need to remain consistent for incremental backups to work. setting up multiple jobs as described in [#9](https://github.com/masc3d/btrfs-sxbackup/issues/9) is currently the only way to accomplish this with btrfs-sxbackup.

**Comment by masc3d** [comment]
However for your usecase I strongly recommend mdraid.

**Comment by tkocher** [comment]
ok, agree.
One other question
can I clone btrfs destination subvolume manually.

and then just change the destination in the destination config file (and
round robin it)?

example:

root@server:/.sxbackup# cat .btrfs-sxbackup.1
[Source]
uuid = 116df805-b7cf-41ae-af7d-c06fbf2f5254
source = /
source-container = .sxbackup/
destination = /mnt/space/backup/sxbackup/local-system/
retention = 3


root@server:/.sxbackup# cat .btrfs-sxbackup.2
[Source]
uuid = 116df805-b7cf-41ae-af7d-c06fbf2f5254
source = /
source-container = .sxbackup/
destination = /mnt/space/backup/sxbackup/local-system2/
retention = 3





Am 28.04.2016 um 14:58 schrieb masc:

**Comment by masc3d** [comment]
no, you cannot use the same source container for multiple destinations, since it would lead to inconsistency as soon as one destination becomes unavailable temporarily and newer incremental snapshots are created. with btrfs-sxbackup you need two backup jobs with separate dedicated source containers for this.. (as shown in #9)

**Comment by masc3d** [comment]
basically you create one backup job, rename `.sxbackup` to eg `.sxbackup-1` and modify `source-container` in `.btrfs-sxbackup` accordingly. then repeat those steps for as many jobs as you wish.
